package com.dailyrecycling.model;

public enum ErrorType {
    START_DATE_LATE_END_DATE,
    EVENT_TYPE_GROSS_AMOUNT_ZERO,
    FINANCING_TYPE_NULL,
    FIRST_LINE_ADDRESS_NULL,
    SECOND_LINE_ADDRESS_NULL,
    CITY_NULL,
    POSTAL_CODE_NULL,
    BCU_NUMBER_NULL,
    CODE_PAYS_ASSURE_NULL,
    DURATION_EXCEEDS_9999
}


